name = "cms-note-downloading"
compatibility_date = "2024-01-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "cms-db"
database_id = "d5284d05-d793-4724-8bd4-7324daed21ba"

# R2 Bucket
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "cms-notes-files"

[vars]
NEXT_PUBLIC_APP_URL = "https://cms-note-downloading.vercel.app"